//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.Phone.Applications.UnitConverter.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.Phone.Applications.UnitConverter.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to add favorite.
        /// </summary>
        public static string AppBar_AddFavorite {
            get {
                return ResourceManager.GetString("AppBar_AddFavorite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to conversions.
        /// </summary>
        public static string AppBar_Conversions {
            get {
                return ResourceManager.GetString("AppBar_Conversions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to swap units.
        /// </summary>
        public static string AppBar_SwapUnits {
            get {
                return ResourceManager.GetString("AppBar_SwapUnits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to add as favorite.
        /// </summary>
        public static string Buttons_addFavorite {
            get {
                return ResourceManager.GetString("Buttons_addFavorite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cancel.
        /// </summary>
        public static string Buttons_cancel {
            get {
                return ResourceManager.GetString("Buttons_cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to conversions.
        /// </summary>
        public static string Buttons_conversions {
            get {
                return ResourceManager.GetString("Buttons_conversions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to delete.
        /// </summary>
        public static string Buttons_delete {
            get {
                return ResourceManager.GetString("Buttons_delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to done.
        /// </summary>
        public static string Buttons_done {
            get {
                return ResourceManager.GetString("Buttons_done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} to {1}.
        /// </summary>
        public static string FavoriteItemLabel {
            get {
                return ResourceManager.GetString("FavoriteItemLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From.
        /// </summary>
        public static string From {
            get {
                return ResourceManager.GetString("From", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CONVERSIONS.
        /// </summary>
        public static string Header_Conversions {
            get {
                return ResourceManager.GetString("Header_Conversions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No favorites.
        /// </summary>
        public static string NoFavorites {
            get {
                return ResourceManager.GetString("NoFavorites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to favorites.
        /// </summary>
        public static string PivotHeader_Favorites {
            get {
                return ResourceManager.GetString("PivotHeader_Favorites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To.
        /// </summary>
        public static string To {
            get {
                return ResourceManager.GetString("To", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to angle.
        /// </summary>
        public static string UnitGroup_Angle {
            get {
                return ResourceManager.GetString("UnitGroup_Angle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to area.
        /// </summary>
        public static string UnitGroup_Area {
            get {
                return ResourceManager.GetString("UnitGroup_Area", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to length.
        /// </summary>
        public static string UnitGroup_Length {
            get {
                return ResourceManager.GetString("UnitGroup_Length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to speed.
        /// </summary>
        public static string UnitGroup_Speed {
            get {
                return ResourceManager.GetString("UnitGroup_Speed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to temp.
        /// </summary>
        public static string UnitGroup_Temp {
            get {
                return ResourceManager.GetString("UnitGroup_Temp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to time.
        /// </summary>
        public static string UnitGroup_Time {
            get {
                return ResourceManager.GetString("UnitGroup_Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to volume.
        /// </summary>
        public static string UnitGroup_Volume {
            get {
                return ResourceManager.GetString("UnitGroup_Volume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to weight.
        /// </summary>
        public static string UnitGroup_Weight {
            get {
                return ResourceManager.GetString("UnitGroup_Weight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Degrees.
        /// </summary>
        public static string Units_Angle_Degrees {
            get {
                return ResourceManager.GetString("Units_Angle_Degrees", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Radians.
        /// </summary>
        public static string Units_Angle_Radians {
            get {
                return ResourceManager.GetString("Units_Angle_Radians", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acre.
        /// </summary>
        public static string Units_Area_Acre {
            get {
                return ResourceManager.GetString("Units_Area_Acre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SqCm.
        /// </summary>
        public static string Units_Area_SqCentimeter {
            get {
                return ResourceManager.GetString("Units_Area_SqCentimeter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SqFt.
        /// </summary>
        public static string Units_Area_SqFeet {
            get {
                return ResourceManager.GetString("Units_Area_SqFeet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SqIn.
        /// </summary>
        public static string Units_Area_SqInch {
            get {
                return ResourceManager.GetString("Units_Area_SqInch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SqM.
        /// </summary>
        public static string Units_Area_SqMeter {
            get {
                return ResourceManager.GetString("Units_Area_SqMeter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SqMi.
        /// </summary>
        public static string Units_Area_SqMile {
            get {
                return ResourceManager.GetString("Units_Area_SqMile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SqMm.
        /// </summary>
        public static string Units_Area_SqMilimeter {
            get {
                return ResourceManager.GetString("Units_Area_SqMilimeter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SqYd.
        /// </summary>
        public static string Units_Area_SqYard {
            get {
                return ResourceManager.GetString("Units_Area_SqYard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Centimeters.
        /// </summary>
        public static string Units_Length_Centimeters {
            get {
                return ResourceManager.GetString("Units_Length_Centimeters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feet.
        /// </summary>
        public static string Units_Length_Feet {
            get {
                return ResourceManager.GetString("Units_Length_Feet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inches.
        /// </summary>
        public static string Units_Length_Inches {
            get {
                return ResourceManager.GetString("Units_Length_Inches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kilometers.
        /// </summary>
        public static string Units_Length_Kilometers {
            get {
                return ResourceManager.GetString("Units_Length_Kilometers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meters.
        /// </summary>
        public static string Units_Length_Meters {
            get {
                return ResourceManager.GetString("Units_Length_Meters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Miles.
        /// </summary>
        public static string Units_Length_Miles {
            get {
                return ResourceManager.GetString("Units_Length_Miles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Millimeters.
        /// </summary>
        public static string Units_Length_Millimeters {
            get {
                return ResourceManager.GetString("Units_Length_Millimeters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yards.
        /// </summary>
        public static string Units_Length_Yards {
            get {
                return ResourceManager.GetString("Units_Length_Yards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Km/H.
        /// </summary>
        public static string Units_Speed_KilometerPerHour {
            get {
                return ResourceManager.GetString("Units_Speed_KilometerPerHour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MPH.
        /// </summary>
        public static string Units_Speed_MilesPerHour {
            get {
                return ResourceManager.GetString("Units_Speed_MilesPerHour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Celsius.
        /// </summary>
        public static string Units_Temp_Celsius {
            get {
                return ResourceManager.GetString("Units_Temp_Celsius", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fahrenheit.
        /// </summary>
        public static string Units_Temp_Fahrenheit {
            get {
                return ResourceManager.GetString("Units_Temp_Fahrenheit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kelvin.
        /// </summary>
        public static string Units_Temp_Kelvin {
            get {
                return ResourceManager.GetString("Units_Temp_Kelvin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Days.
        /// </summary>
        public static string Units_Time_Days {
            get {
                return ResourceManager.GetString("Units_Time_Days", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hours.
        /// </summary>
        public static string Units_Time_Hours {
            get {
                return ResourceManager.GetString("Units_Time_Hours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Milliseconds.
        /// </summary>
        public static string Units_Time_Milliseconds {
            get {
                return ResourceManager.GetString("Units_Time_Milliseconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minutes.
        /// </summary>
        public static string Units_Time_Minutes {
            get {
                return ResourceManager.GetString("Units_Time_Minutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seconds.
        /// </summary>
        public static string Units_Time_Seconds {
            get {
                return ResourceManager.GetString("Units_Time_Seconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Years.
        /// </summary>
        public static string Units_Time_Years {
            get {
                return ResourceManager.GetString("Units_Time_Years", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cups.
        /// </summary>
        public static string Units_Volume_Cups {
            get {
                return ResourceManager.GetString("Units_Volume_Cups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gallons (US).
        /// </summary>
        public static string Units_Volume_Gallons {
            get {
                return ResourceManager.GetString("Units_Volume_Gallons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gallons (UK).
        /// </summary>
        public static string Units_Volume_Imperial_Gallons {
            get {
                return ResourceManager.GetString("Units_Volume_Imperial_Gallons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ounces (UK).
        /// </summary>
        public static string Units_Volume_Imperial_Ounces {
            get {
                return ResourceManager.GetString("Units_Volume_Imperial_Ounces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pints (UK).
        /// </summary>
        public static string Units_Volume_Imperial_Pints {
            get {
                return ResourceManager.GetString("Units_Volume_Imperial_Pints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Liters.
        /// </summary>
        public static string Units_Volume_Liters {
            get {
                return ResourceManager.GetString("Units_Volume_Liters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ounces (US).
        /// </summary>
        public static string Units_Volume_Ounces {
            get {
                return ResourceManager.GetString("Units_Volume_Ounces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quarts.
        /// </summary>
        public static string Units_Volume_Quarts {
            get {
                return ResourceManager.GetString("Units_Volume_Quarts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grams.
        /// </summary>
        public static string Units_Weight_Grams {
            get {
                return ResourceManager.GetString("Units_Weight_Grams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tons (UK).
        /// </summary>
        public static string Units_Weight_ImperialTons {
            get {
                return ResourceManager.GetString("Units_Weight_ImperialTons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kilograms.
        /// </summary>
        public static string Units_Weight_Kilograms {
            get {
                return ResourceManager.GetString("Units_Weight_Kilograms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MTons.
        /// </summary>
        public static string Units_Weight_MetricTons {
            get {
                return ResourceManager.GetString("Units_Weight_MetricTons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ounces.
        /// </summary>
        public static string Units_Weight_Ounces {
            get {
                return ResourceManager.GetString("Units_Weight_Ounces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pounds.
        /// </summary>
        public static string Units_Weight_Pounds {
            get {
                return ResourceManager.GetString("Units_Weight_Pounds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tons (US).
        /// </summary>
        public static string Units_Weight_Tons {
            get {
                return ResourceManager.GetString("Units_Weight_Tons", resourceCulture);
            }
        }
    }
}
